modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="immersive_ore_expedition.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="journeymap"
    type="optional"
    versionRange="[1.21-6.0.0-beta.1,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="ae2"
    type="required"
    versionRange="${ae2_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ae2cs"
    type="required"
    versionRange="${ae2cs_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geore"
    type="required"
    versionRange="${geore_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="geore_additions"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="extendedae"
    type="optional"
    versionRange="${extendedae_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="immersiveengineering"
    type="optional"
    versionRange="${ie_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="immersivepetroleum"
    type="optional"
    versionRange="${ip_version_range}"
    ordering="AFTER"
    side="BOTH"
