modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="ioe_nether_geodes"
version="${mod_version}"
displayName="Immersive Ore Expedition: Nether Geodes"
authors="${mod_authors}"
description='''Sub-lava Nether geodes that spawn only beneath giant Nether lava lakes.'''

[[dependencies.ioe_nether_geodes]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ioe_nether_geodes]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ioe_nether_geodes]]
    modId="ioe_core"
    type="required"
    versionRange="[0.1.7,)"
    ordering="AFTER"
    side="BOTH"
